import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class HelloName {
    public String getGreeting(String name) {
        return "Hello " + name;
    }

    public String AskUserForAName() {
    	Scanner in= new Scanner(System.in);
    	System.out.println("Input your Name");
		return in.nextLine();
				
    }
    public static void main(String[] args) {
    	HelloName hello = new HelloName();
        System.out.println(hello.getGreeting(hello.AskUserForAName()));
    }
}
