/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;

public class AppTest {
    
	@DataProvider(name="names")
	public Object[][] names(){
		return new Object[][]{
			{"Steven"}, {"Seven"}, {"A"}
		};
	}	
	
	@Test (dataProvider="names")
    public void appHasAGreeting(String name) {
        HelloName classUnderTest = new HelloName();
        assertEquals(classUnderTest.getGreeting(name), "Hello "+ name, "app should greets me");        
	}
	
	@Test public void whetherGreetedNameIsTheOneWeGave(){
		System.setIn(new ByteArrayInputStream("Some name".getBytes()));
		HelloName hello = new HelloName();
		String nameGiven = hello.AskUserForAName();
		String nameWeGreet = hello.getGreeting(nameGiven);
		assertEquals(nameWeGreet, "Hello "+ nameGiven);
	}
}
